name: maxcutpool
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.9
  - matplotlib
  - pytorch=2.1.2
  - pytorch-cuda=12.1
  - torchinfo
  - jupyter
  - notebook
  - numpy<2
  - pandas
  - pip
  - pip:
      - torch-geometric==2.5.0
      - cvxopt
      - cvxpy
      - einops
      - gravis
      - hydra-core
      - hydra-optuna-sweeper
      - hydra-joblib-launcher
      - imageio
      - omegaconf
      - git+https://github.com/gsp-eeg/pygsp2
      - lightning
      - tensorboard
      - -r requirements.txt