# @package _global_

defaults:
  - reload_default


dataset:
  name: PyGSPDataset
  hparams:
    dataset: RandomRegular
  params:
    N: 100            # Number of nodes
    k: 3              # Number of connections, or degree, of each node
    seed: 0           # Seed for the random number generator